apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: hygieia-ui
    spec:
  type: LoadBalancer
  ports:
   - name: "3000"
     port: 3000
     targetPort: 80
  selector:
    app: hygieia-ui
